name: ESP-IDF CI

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v4.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Prepare enviroment
      run: |
        apt update
        apt install -y xxd

    - name: ESP-IDF build
      run: |
        cd platform/esp
        . $IDF_PATH/export.sh
        idf.py build
