name: Linux CI

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Prepare enviroment
        run: |
          sudo apt update
          sudo apt install -y \
            cmake ninja-build clang \
            libavahi-compat-libdnssd-dev \
            libssl-dev python3-pip
          sudo pip3 install cpplint

      - name: Linux build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
